WebCrawler.WebApplication/Models/TestResultModel.cs
using System.Collections.Generic;
using WebCrawler.Data;
using WebCrawler.Logic;

namespace WebCrawler.WebApplication.Models
{
    public class TestResultModel
    {
        public string Url { get; set; }
        public IEnumerable<PerformanceResult> Performance { get; set; }
        public IEnumerable<string> UrlsFoundOnlyInSitemap { get; set; }
        public IEnumerable<string> UrlsFoundOnlyInWebsite { get; set; }
    }
}

WebCrawler.WebApplication/Models/TestsModel.cs
using System.Collections.Generic;
using WebCrawler.Data;

namespace WebCrawler.WebApplication.Models
{
    public class TestsModel
    {
        public IEnumerable<Test> Tests { get; set; } 
    }
}

WebCrawler.WebApplication/Models/UserInputModel.cs
namespace WebCrawler.WebApplication.Models
{
    public class UserInputModel
    {
        public string Url { get; set; }
    }
}

WebCrawler.WebApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using WebCrawler.Logic;
using WebCrawler.Logic.Validators;
using WebCrawler.WebApplication.Models;
using WebCrawler.WebApplication.Services;

namespace WebCrawler.WebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly DbWorker _dbWorker;
        private readonly CrawlerService _crawlerService;
        private readonly InputValidator _inputValidator;

        public HomeController(DbWorker dbWorker, CrawlerService crawlerService, InputValidator inputValidator)
        {
            _dbWorker = dbWorker;
            _crawlerService = crawlerService;
            _inputValidator = inputValidator;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new TestsModel() {Tests=_dbWorker.GetAllTests()});
        }

        [HttpPost]
        public IActionResult Index(UserInputModel input)
        {
            string errors;
            var inputParamtersAreValid = _inputValidator.InputParameters(input.Url, out errors);
            if (!inputParamtersAreValid)
            {
                ModelState.AddModelError("Url", errors);
            }

            if(ModelState.IsValid)
            {
                _crawlerService.Crawl(input.Url);
            }

            var testsModel = new TestsModel() { Tests = _dbWorker.GetAllTests() };

           return View(testsModel);  
        }
    }
}

WebCrawler.WebApplication/Controllers/ResultsController.cs
using Microsoft.AspNetCore.Mvc;
using WebCrawler.WebApplication.Models;
using WebCrawler.Logic;
using System.Linq;

namespace WebApplication.Controllers
{
    public class ResultsController : Controller
    {
        private readonly DbWorker _dbWorker;

        public ResultsController(DbWorker dbWorker)
        {
            _dbWorker = dbWorker;
        }

        public IActionResult Index(int id)
        {
            var testUrl = _dbWorker.GetUrlByTestId(id);
            var performance = _dbWorker.GetPerformanceResultsByTestId(id).ToList();
            var urlsFoundOnlyInSitemap=_dbWorker.GetUrlsFoundOnlyInSitemapByTestId(id);
            var urlsFoundOnlyInWebsite = _dbWorker.GetUrlsFoundOnlyInWebsiteByTestId(id); 

            return View(new TestResultModel() { Url = testUrl, Performance = performance, UrlsFoundOnlyInSitemap = urlsFoundOnlyInSitemap, UrlsFoundOnlyInWebsite = urlsFoundOnlyInWebsite });
        }
    }
}

WebCrawler.WebApplication/Views/Home/Index.cshtml
@model WebCrawler.WebApplication.Models.TestsModel
@{
    ViewData["Title"] = "Start page";
}

<div class="container mt-5">

    @await Html.PartialAsync("_Form", new UserInputModel())

    <div class="row text-center mt-5 table-responsive">
        <h1 class="h2">Test results</h1>
        <table id="testsTable" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th class="w-50">Website</th>
                    <th class="w-25">Date</th>
                    <th class="w-25"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var test in Model.Tests)
                {
                    <tr>
                        <td>@test.Url</td>
                        <td>@test.Date</td>
                        <td><a asp-action="Index" asp-controller="Results" asp-route-id=@test.Id>see details</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#testsTable').DataTable({
            searching: false,
            ordering: false,
            order: false,
            "pageLength": 50
        });
    });
</script>

WebCrawler.WebApplication/Views/Home/_Form.cshtml
@model WebCrawler.WebApplication.Models.UserInputModel

<form method="post" asp-action="Index" asp-antiforgery="false">
    <div class="d-flex">
        <div class="p-2">
            <label class="col-form-label">Enter a website</label>
        </div>
        <div class="p-2 flex-fill">
            <input asp-for="Url" type="text" required class="form-control">
        </div>
        <div class="p-2">
            <button type="submit" class="btn btn-dark">Submit</button>
        </div>
    </div>
    <div asp-validation-summary="All"></div>
</form>

WebCrawler.WebApplication/Views/Results/Index.cshtml
@model WebCrawler.WebApplication.Models.TestResultModel
@{
    ViewData["Title"] = "Test result page";
}

<div class="container mt-5">
    <div class="row border-bottom">
        <h1 class="h2">@Model.Url</h1>
    </div>

    <div class="row mt-5 table-responsive d-flex">
        <h1 class="h2">PERFORMANCE</h1>
        <table id="performanceTable" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th class="col">Url</th>
                    <th class="flex-column">Timing</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var result in Model.Performance)
                {
                    <tr>
                        <td>@result.Url</td>
                        <td class="text-center">@result.ResponseTime</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>



    <div class="row mt-5 table-responsive">
        <h1 class="h2">URLs NOT FOUND AT WEBSITE</h1>
        <table id="onlySitemapUrlsTable" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Url</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var url in Model.UrlsFoundOnlyInSitemap)
                {
                    <tr>
                        <td>@url</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="row mt-5 table-responsive">
        <h1 class="h2">URLs NOT FOUND AT SITEMAP</h1>
        <table id="onlyWebsiteUrlsTable" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Url</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var url in Model.UrlsFoundOnlyInWebsite)
                {
                    <tr>
                        <td>@url</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


<script>
    $(document).ready(function () {
        $('#performanceTable').DataTable({
            searching: false,
            ordering: false,
            order: false,
            "pageLength": 50
        });
    });
    $(document).ready(function () {
        $('#onlySitemapUrlsTable').DataTable({
            searching: false,
            ordering: false,
            order: false,
            "pageLength": 50
        });
    });
    $(document).ready(function () {
        $('#onlyWebsiteUrlsTable').DataTable({
            searching: false,
            ordering: false,
            order: false,
            "pageLength": 50
        });
    });
</script>

WebCrawler.WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebCrawler</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @RenderSection("Scripts", required: false)
</body>

</html>